### ISSUE TITLE
Argument list for TinyTIFFWriter_open

### ISSUE THREAD

**Issue by wenxuanliang** [jkriege2/TinyTIFF#13]
In the "tinytiffwriter.h", the function is defined as:
TINYTIFF_EXPORT TinyTIFFWriterFile* TinyTIFFWriter_open(const char* filename, uint16_t bitsPerSample, enum TinyTIFFWriterSampleFormat sampleFormat, uint16_t samples, uint32_t width, uint32_t height, enum TinyTIFFWriterSampleInterpretation sampleInterpretation);

In the example code, the parameter TinyTIFFWriterSampleFormat sampleFormat seems to be omitted:
 TinyTIFFWriterFile* tif=TinyTIFFWriter_open("extcmake_tinytiff_test.tif", 8, 1, 32, 32);

Confused

**Comment by jkriege2** [comment]
has been fixed via https://github.com/jkriege2/TinyTIFF/commit/5f1f503778117df25c2f38bac4d06c7bdf45e94d
