### ISSUE TITLE
24 bit images support absence

### ISSUE THREAD

**Issue by Zvictoria** [jkriege2/TinyTIFF#2]
Hi there, thanks for your work. As I found out on practice (and looking into your code) the library doesn't support input 24 bit tiff images. I failed to find any mentioning of it in your readme - could you please add?
It will help others in their library estimation.
...and it would be cool if you add such support. It doesn't look difficult :)

**Comment by jkriege2** [comment]
added initial support to TinyTIFFWriter with https://github.com/jkriege2/TinyTIFF/commit/0bbc40ddc31d6b6f1d15f607c22fe536823a4a7d
