### ISSUE TITLE
Add vcpkg support.

### ISSUE THREAD

**Issue by sidy3d** [jkriege2/TinyTIFF#29]
Hi,

Thanks for this great library. Would you consider adding it to the [vcpkg ](https://github.com/microsoft/vcpkg) package manager? This would make much it easier to consume in projects and build on multiple platforms.

I would do this myself but I'm not skilled enough in CMake.

Thanks,

**Comment by EfesX** [comment]
@sidy3d I'll try to add this library to vcpkg. PR will be submitted soon.

**Comment by jkriege2** [comment]
Do so, I'm happy to merge anything that you push ... I also didn't work with vcpkg so far ...

**Comment by sidy3d** [comment]
The link issue has been merged. Thank you very much adding the library to vcpkg! Closing the issue.
