### ISSUE TITLE
Could you provide a tiff writing example with header data?

### ISSUE THREAD

**Issue by KaiWangCanada** [jkriege2/TinyTIFF#3]
I'm trying to add header data to the tiff file, but found it not easy.

The function I'm looking into is this:

`
inline void TinyTIFFWriter_fopen(TinyTIFFFile* tiff, const char* filename) {
`

Looks like there is no header info passed in as parameters.

What shall I do? 

Thanks!

**Comment by jkriege2** [comment]
Hi!

the library does not support explicit access to the headers of the frames. It writes the absolute bare minimum in TinyTIFFWriter_writeImage() and can additionally write a description in TinyTIFFWriter_close() ... if you need more, you would need to extend one of these functions.
This lib was intended for super-fast writing of multi-frame TIFFs where all frames have equal properties (which allows some magic with pointers inside the file!) and thus dos not implement any features that were not necessary for the inteded use (at the time ;-)

Hope that helps,
JAN

**Comment by KaiWangCanada** [comment]
Thank you, kriege :)
