### ISSUE TITLE
16bit grayscale + alpha

### ISSUE THREAD

**Issue by Eta76** [jkriege2/TinyTIFF#7]
I downloaded this project, because it seems to be one of the smaller libs for generating a tiff.

In my application, I would like to generate a 16bit grayscale image, including transparency.
So i modified a test, to see some of the possibilities. During this test I noticed a small bug.

I have still no experience using git, so I will just show my changes here.

**\repos\jkriege2\TinyTIFF\tests\tinytiffwriter_test\tinytiffwriter_test.cpp**

**New test:**
`	std::cout << "WRITING 16-Bit UINT + 16-bit alpha TIFF\n";
	tiff = TinyTIFFWriter_open("test1616.tif", 16, 2, WIDTH, HEIGHT);
	TinyTIFFWriter_writeImage(tiff, image1616);
	TinyTIFFWriter_close_withmetadatadescription(tiff, 100, 200, 300, 1e-4);
	libtiffTestRead<GrayAndAlpha>("test1616.tif", image1616, WIDTH, HEIGHT);`

**Using new allocated data structure:**
`struct GrayAndAlpha
{
	uint16_t	gray16;
	uint16_t	alpha16;
};
GrayAndAlpha* image1616 = (GrayAndAlpha*)calloc(WIDTH*HEIGHT, sizeof(GrayAndAlpha));
`
**Fill the data:**
`			image1616[i].gray16 = image16[i];
			image1616[i].alpha16 = image16i[i];`

**Fix:**
**\repos\jkriege2\TinyTIFF\src\tinytiffwriter.c**
gray with alpha is two channels, so don't use the RGB PHOTOMETRIC
`    if (tiff->samples==1 || tiff->samples == 2) {
        TinyTIFFWriter_writeIFDEntrySHORT(tiff, TIFF_FIELD_PHOTOMETRICINTERPRETATION, TIFF_PHOTOMETRIC_BLACKISZERO);
    } else if (tiff->samples>2) {
        TinyTIFFWriter_writeIFDEntrySHORT(tiff, TIFF_FIELD_PHOTOMETRICINTERPRETATION, TIFF_PHOTOMETRIC_RGB);
    }`

**Comment by Eta76** [comment]
Opening the files using the tinytiffreader_test.exe also gives some problems in, since the files are written as TIFF_PLANARCONFIG_CHUNKY:

**\repos\jkriege2\TinyTIFF\src\tinytiffreader.c**
`        if (tiff->currentFrame.samplesperpixel>1 && tiff->currentFrame.planarconfiguration!=TIFF_PLANARCONFIG_PLANAR) {
            tiff->wasError=TINYTIFFREADER_TRUE;
#ifdef HAVE_STRCPY_S
            strcpy_s(tiff->lastError, TIFF_LAST_ERROR_SIZE, "only planar TIFF files are supported by this library\0");
#else
            strcpy(tiff->lastError, "only planar TIFF files are supported by this library\0");
#endif
            return TINYTIFFREADER_FALSE;
        }`

**tinytiffwriter.c**
`TinyTIFFWriter_writeIFDEntrySHORT(tiff, TIFF_FIELD_PLANARCONFIG, 1);`

with
`#define TIFF_PLANARCONFIG_CHUNKY 1`

**Comment by jkriege2** [comment]
Hi!

thanks for reporting ... could you do a pul-request for your fixes?

Best,
JAN

**Comment by Eta76** [comment]
As a long term SourceSafe and TeamFoundation user I have zero experience with Git(Hub) :-)

My fix was changing:
\source\repos\jkriege2\TinyTIFF\src\tinytiffwriter.c - line 864:
      if  (tiff->samples==1) {
into:
      if (tiff->samples==1 || tiff->samples==2) {

Gimp still complained about a missing "ExtraChannels" field, but allowed me to select the extra channel as:
- non-premultiplied alpha
- Premultiplied alpha
- Channel

Saving the file in GIMP and opening the new file gave the other error, which I did not yet look into how to resolve.

Trying to work with GIMP... Its not ideal as a height map editor. So I gave up this direction.

I have added my modified test, so hopefully this is helpful to some one.

[tinytiffwriter_test.zip](https://github.com/jkriege2/TinyTIFF/files/5197100/tinytiffwriter_test.zip)

**Comment by jkriege2** [comment]
Hi!

sorry for the long delay ... I just wanted to let you know that I'm currently working on a solution (slightly different/more general than what you proposed) and I hope that solves the problem for you. I'll let you know when I push the changes. Maybe you can counter-check them whether they work for you.

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I improved TinyTIFFWriter to support your usecase. the commit is https://github.com/jkriege2/TinyTIFF/commit/037bb1b0db7f7825a656ba3ff8cd4d9d6f319101

Could you have a look whether this solves your problem?

you need these calls:

```c++
TinyTIFFWriterFile* tiff = TinyTIFFWriter_open(filename, 16, TinyTIFFWriter_UInt, 1, WIDTH,HEIGHT, TinyTIFFWriter_GreyscaleAndAlpha);
TinyTIFFWriter_writeImageMultiSample(tiff, imagedata, TinyTIFF_Interleaved, TinyTIFF_Interleaved);
TinyTIFFWriter_close(tiff);
```

**Comment by jkriege2** [comment]
BTW: Please reopen this issue, if it does not work for you!

**Comment by Eta76** [comment]
Thanks for they update, you have been busy.
So I modified the write test, to save a 16bit grey+alpha, but opening the file in GIMP makes it completely transparant.
the "test_ga.tif" (8bit grey+alpha) does look correctly.
Possibly I am doing something wrong, this is my addition to the tinytiffwriter_test.cpp
	std::vector<uint16_t> image16a(WIDTH*HEIGHT*2, 0);
	write1ChannelTestData(image16a.data(), WIDTH, HEIGHT, PATTERNSIZE, 2);
	performWriteTest("WRITING 16-Bit UINT GREY alpha TIFF", "test16a.tif", image16a.data(), WIDTH, HEIGHT, 2, TinyTIFFWriter_GreyscaleAndAlpha, test_results);

As a side note:
i don't hope people will be using the test framework code as a baseline for performance critical software, because I expect these type of lines to cause a lot of heap allocations:
std::string desc=std::to_string(WIDTH)+"x"+std::to_string(HEIGHT)+"pix/"+std::to_string(bits)+"bit/"+std::to_string(SAMPLES)+"ch/"+std::to_string(FRAMES)+"frames";
a sprintf would have saved all heap allocations, and simply use stack space.

**Comment by jkriege2** [comment]
Hi.
About the 16bit gray+alpha: did you also call writeALPHATestData(...) for your data? Otherwise all alpha-samples are 0, as the write1channelTestData() only writes data for 1 channel ... that could explain, why the data is not displayed as expected ... 

BTW: did you compile against libtiff? Then the contents of the file should be tested against reading with libtiff and comparing against the input data ... did that come up clean?

About performance:I hope so too ... in the end it's not intended for that purpose ... have a look at https://github.com/jkriege2/TinyTIFF/blob/master/tests/tinytiffwriter_speedtest/tinytiffwriter_speedtest.cpp for code which is tailored towards performance tests ... the simple test is intended to check the basic functioning ...

**Comment by Eta76** [comment]
Unfortunately I dont have libtiff compiled.
So adding the writeALPHATestData indeed helped to get alpha values, thanks for that.
So I added this line:
     writeALPHATestData(image16a.data(), 1, WIDTH, HEIGHT, 2);

But I still see differences in the output, when comparing to the 8bit file. Possibly just a problem of the writeALPHATestData.
![image](https://user-images.githubusercontent.com/40275746/97029439-bd7a9000-155d-11eb-83cb-091dc8aa2f00.png)

When changing the alpha value calculation I get a better result:
            imagergba[i*CHANNELSINDATA+alpha_channel]=
				TIMAGESAMPLETYPE((**float**(r2max-r2) * std::numeric_limits<TIMAGESAMPLETYPE>::max()) / r2max);
			    //TIMAGESAMPLETYPE((r2max-r2)*std::numeric_limits<TIMAGESAMPLETYPE>::max()/r2max);

![image](https://user-images.githubusercontent.com/40275746/97032665-780c9180-1562-11eb-97f0-a758441fc03b.png)

I do see a minor warning during Gimp import:
ASCII value for tag "ImageDescription" contains null byte in value; value incorrectly truncated during reading due to implementation limitations.
Message repeated 3 times.

**Comment by Eta76** [comment]
Hi,

 

Thanks for the updated library. I did post my result and a question, to this topic, but since it is closed, you possibly missed it

https://github.com/jkriege2/TinyTIFF/issues/7

 

So see my latest post, I needed to make a changes in the sample app, before the data was exported correctly.

 

Edgar

**Comment by jkriege2** [comment]
Hi@

Sorry for mylate response ... i'm currently occupied with some Medical Problems.

Yes, it may be that there are some issues with calculating the alpha-values. Since the test-program compares against the generated alpha values that were also used for writing, this is not an issue for the test itself. If you would like to see the nicer output, please post a pull-request with your modification ... then I can merge it ...

**Comment by jkriege2** [comment]
About the warning: I'm aware of this, but didn't have time to fix it ... and since it's non-critical ... it may take me a few more weeks until I find time for that ... it would help though, if you could open a new issue with the error description, so it doesn't get lost.
