### ISSUE TITLE
Issues with loading 16bit single channel gray image: loaded values getting shifted to the right by 5 columns.

### ISSUE THREAD

**Issue by bala1144** [jkriege2/TinyTIFF#8]
Hi,

I am using TinyTiff to load 16bit gray tiff image. 

When I load smaller images, it loads perfectly.  But when I try to load a image of  2048 x 2048 resolution.  The load image is misaligned slightly.
 
Following is the code, I am using to load the file. I am also using the openCV to load the same image for debugging purpose.

`char* tiff_file_in_pt = "C:\\Users\\xxxx\\xxxx\\projects\\testImages\\2K_tiff_image.tif";
	std::cout << " tiffl in file " << tiff_file_in_pt << std::endl;

	// load the tiff interface
	TinyTIFFReaderFile* tiffr = NULL;
	tiffr = TinyTIFFReader_open(tiff_file_in_pt);
	bool ok = true;
	if (!tiffr) {
		std::cout << "    ERROR reading (not existent, not accessible or no TIFF file)\n";
	}
	else {
		uint32_t width = TinyTIFFReader_getWidth(tiffr);
		uint32_t height = TinyTIFFReader_getHeight(tiffr);
		uint16_t* image = (uint16_t*)calloc(width * height, sizeof(uint16_t));
		TinyTIFFReader_getSampleData(tiffr, image, 0);
		if (TinyTIFFReader_wasError(tiffr)) { ok = false; std::cout << "   ERROR:" << TinyTIFFReader_getLastError(tiffr) << "\n"; }

		cv::Mat mat1(cv::Size(width, height), CV_16UC1, image);
		std::cout << "mat1: \n" << mat1(cv::Rect(0,0,10,10)) << std::endl << std::endl;;
		
		// read the same image using opencv and display the results
		cv::Mat input_Noisy_Img = cv::imread(tiff_file_in_pt, CV_LOAD_IMAGE_ANYDEPTH);
		std::cout << "input_Noisy_Img: \n" << input_Noisy_Img(cv::Rect(0, 0, 10, 10)) << std::endl;
		std::cout << "Diff Img : \n" << mat1(cv::Rect(0, 0, 10, 10)) - input_Noisy_Img(cv::Rect(0, 0, 10, 10)) << std::endl;

		free(image);
	}
	TinyTIFFReader_close(tiffr);`

Following is the result of this code:
` tiffl in file C:\Users\xxx\xxxx\projects\testImages\2K_tiff_image.tif
 width :2048 Height 2048
mat1:
[18761, 42, 8, 128, 255, 185, 131, 127, 104, 111;
 99, 102, 99, 105, 268, 213, 136, 127, 102, 103;
 97, 104, 99, 105, 160, 208, 142, 114, 117, 109;
 106, 104, 103, 97, 165, 179, 139, 104, 100, 106;
 99, 102, 96, 109, 159, 116, 143, 122, 113, 140;
 108, 105, 106, 104, 154, 124, 142, 144, 161, 120;
 101, 107, 105, 105, 161, 125, 130, 153, 155, 132;
 99, 109, 108, 112, 122, 107, 116, 165, 199, 154;
 107, 94, 99, 105, 100, 114, 123, 137, 190, 185;
 114, 113, 102, 98, 103, 96, 109, 119, 132, 115]

input_Noisy_Img:
[255, 185, 131, 127, 104, 111, 105, 95, 106, 120;
 268, 213, 136, 127, 102, 103, 116, 118, 106, 114;
 160, 208, 142, 114, 117, 109, 101, 114, 118, 115;
 165, 179, 139, 104, 100, 106, 128, 123, 113, 104;
 159, 116, 143, 122, 113, 140, 126, 114, 123, 130;
 154, 124, 142, 144, 161, 120, 109, 115, 110, 107;
 161, 125, 130, 153, 155, 132, 118, 112, 123, 116;
 122, 107, 116, 165, 199, 154, 116, 108, 98, 98;
 100, 114, 123, 137, 190, 185, 133, 120, 112, 102;
 103, 96, 109, 119, 132, 115, 118, 93, 103, 106]

Diff Img :
[18506, 0, 0, 1, 151, 74, 26, 32, 0, 0;
 0, 0, 0, 0, 166, 110, 20, 9, 0, 0;
 0, 0, 0, 0, 43, 99, 41, 0, 0, 0;
 0, 0, 0, 0, 65, 73, 11, 0, 0, 2;
 0, 0, 0, 0, 46, 0, 17, 8, 0, 10;
 0, 0, 0, 0, 0, 4, 33, 29, 51, 13;
 0, 0, 0, 0, 6, 0, 12, 41, 32, 16;
 0, 2, 0, 0, 0, 0, 0, 57, 101, 56;
 7, 0, 0, 0, 0, 0, 0, 17, 78, 83;
 11, 17, 0, 0, 0, 0, 0, 26, 29, 9]`

Finally, If we notice the mat1 loaded with TinyTiff,  we can see unrelated values in the first 5 columns. Its looks like the values are getting shifted by 5 columns.

It would be great, if you can help me with this issue.

**Comment by jkriege2** [comment]
Hi!

thanks for reporting ... could you upload the file? Does the problem appear with this file only, or also with other files of the same size?

Best,
JAN

**Comment by bala1144** [comment]
Hi,

I have the attached the tiff image in the zip file.
I tried to analyse the issue. Whenever, I load a tiff image with single slice, I notice these 4 values [18761, 42,  8, 128]  are added to the start of memory like some kind of header. I couldn't understand, what it is. 

Further, I created a Tiff image stack from the same tiff image. When I loaded this tiff stack, I didn't see these values added. I have also attached the tiff stack in this for you reference.
[2K_source_Stack.zip](https://github.com/jkriege2/TinyTIFF/files/5282369/2K_source_Stack.zip)
[2K_tiff_image.zip](https://github.com/jkriege2/TinyTIFF/files/5282246/2K_tiff_image.zip)

**Comment by jkriege2** [comment]
I'm currently looking into the problem ... at least I can already confirm it ;-) ... but this might take some time.

One question: may I check in the images you provided as test datasets and distribute them with the library?

**Comment by jkriege2** [comment]
Hi! 
I think I found the bug: The problem was that the table with the strip-offsets was the last bytes in the file and there was a bug that prevented it from beeing read (I used < instead of <= ...). The fix was just pushed as https://github.com/jkriege2/TinyTIFF/commit/8aea9d12fd698a8684a0c5fcb71a88996f40b5d9

Could you confirm that it works now?

Thanks,
JAN

PS: Can I publish the two TIFFs you provided above as test data?

**Comment by bala1144** [comment]
Hi,

Thanks for responding and fixing the bug.  I have n't tested the fix yet.

Regarding the TIFF images, I have to talk to my supervisor to give you an answer. Can I confirm that by the end of the week ?

Regards,
Bala

**Comment by jkriege2** [comment]
Yeah no problem ... the files do not have to contain that actual data ... I'm more interested in files with the same characteristic, as I use them for tests ...

Please let me know, whether my fix solved your problem, when you found time to test.

BTW: Out of curiosity: What are you working on?

Best,
JAN

**Comment by bala1144** [comment]
Hi,

I tested the fix, it seems the bug is not fixed yet. I am still getting the same issue.

PS: I am working on neutron imaging

**Comment by jkriege2** [comment]
Hmmm ... could you check again? I just pushed some more fixes/reworks.

I also reworked the test prograns abd tinytiffreader_test has calls for your TIFF-files (commented out) and check the result of TinyTIFFReader against libTIFF ...

Would be great, if you could have a second look!

Thanks,
JAN

**Comment by bala1144** [comment]
Hi,

I tested it again, still it is not working.
Here is the code, I am using

`
void read_tiff_Image_tester()
{
	
	//char* tiff_file_in_pt = "C:\\Users\\Bala\\Documents\\projects\\testImages\\test_10x10_stack3.tif";
	char* tiff_file_in_pt = "C:\\Users\\Bala\\Documents\\projects\\testImages\\2K_tiff_image.tif";
	std::cout << " tiffl in file " << tiff_file_in_pt << std::endl;

	// load the tiff interface
	TinyTIFFReaderFile* tiffr = NULL;
	tiffr = TinyTIFFReader_open(tiff_file_in_pt);
	bool ok = true;
	if (!tiffr) {
		std::cout << "    ERROR reading (not existent, not accessible or no TIFF file)\n";
	}
	else {
		uint32_t width = TinyTIFFReader_getWidth(tiffr);
		uint32_t height = TinyTIFFReader_getHeight(tiffr);
		uint16_t* image = (uint16_t*)calloc(width * height, sizeof(uint16_t));
		TinyTIFFReader_getSampleData(tiffr, image, 0);
		if (TinyTIFFReader_wasError(tiffr)) { ok = false; std::cout << "   ERROR:" << TinyTIFFReader_getLastError(tiffr) << "\n"; }

		cv::Mat mat1(cv::Size(width, height), CV_16UC1, image);
		std::cout << "mat1: \n" << mat1(cv::Rect(0,0,10,10)) << std::endl << std::endl;

		// read the same image using opencv and display the results
		cv::Mat input_Noisy_Img = cv::imread(tiff_file_in_pt, CV_LOAD_IMAGE_ANYDEPTH);
		std::cout << "input_Noisy_Img: \n" << input_Noisy_Img(cv::Rect(0, 0, 10, 10)) << std::endl;

		free(image);
	}
	TinyTIFFReader_close(tiffr);
}
`

Here is the result : 
`
 tiffl in file C:\Users\Bala\Documents\projects\testImages\2K_tiff_image.tif
mat1:
[18761, 42, 8, 128, 255, 185, 131, 127, 104, 111;
 99, 102, 99, 105, 268, 213, 136, 127, 102, 103;
 97, 104, 99, 105, 160, 208, 142, 114, 117, 109;
 106, 104, 103, 97, 165, 179, 139, 104, 100, 106;
 99, 102, 96, 109, 159, 116, 143, 122, 113, 140;
 108, 105, 106, 104, 154, 124, 142, 144, 161, 120;
 101, 107, 105, 105, 161, 125, 130, 153, 155, 132;
 99, 109, 108, 112, 122, 107, 116, 165, 199, 154;
 107, 94, 99, 105, 100, 114, 123, 137, 190, 185;
 114, 113, 102, 98, 103, 96, 109, 119, 132, 115]

input_Noisy_Img:
[255, 185, 131, 127, 104, 111, 105, 95, 106, 120;
 268, 213, 136, 127, 102, 103, 116, 118, 106, 114;
 160, 208, 142, 114, 117, 109, 101, 114, 118, 115;
 165, 179, 139, 104, 100, 106, 128, 123, 113, 104;
 159, 116, 143, 122, 113, 140, 126, 114, 123, 130;
 154, 124, 142, 144, 161, 120, 109, 115, 110, 107;
 161, 125, 130, 153, 155, 132, 118, 112, 123, 116;
 122, 107, 116, 165, 199, 154, 116, 108, 98, 98;
 100, 114, 123, 137, 190, 185, 133, 120, 112, 102;
 103, 96, 109, 119, 132, 115, 118, 93, 103, 106]
`

I havent compared it with libTiff, I need to build. I will compare it and update the results later.

Thanks,
Bala.

**Comment by jkriege2** [comment]
Weird ... for me it works ... I output the first 10 Pixels while reading the file (and check every pixel against libTIFF). The output is:
```
reading '2K_tiff_image.tif' with tinytiff and libtiff and checking read contents ... filesize = 8.001 MBytes
    libTIFF: opening file with     [duration: 200.000000ns ]
    libTIFF: frames: 1     [duration: 18.2 us  =  18.200000us ]
    TinyTIFF: opening file with     [duration: 29.200000us ]
    TinyTIFF: frames: 1     [duration: 5.3 us  =  5.300000us ]
   frame: 0
     tinyTIFF: width=2048, height=2048, bitspersample=16, samplesperpixel=1
TIFF Directory at offset 0x800008 (8388616)
  Image Width: 2048 Image Length: 2048
  Resolution: 72, 72 pixels/inch
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 32
  Planar Configuration: single image plane
     libTIFF:  width=2048, height=2048, bitspersample=16, samplesperpixel=1
          f0s0i0: tiny=255 lib=255
          f0s0i1: tiny=185 lib=185
          f0s0i2: tiny=131 lib=131
          f0s0i3: tiny=127 lib=127
          f0s0i4: tiny=104 lib=104
          f0s0i5: tiny=111 lib=111
          f0s0i6: tiny=105 lib=105
          f0s0i7: tiny=95 lib=95
          f0s0i8: tiny=106 lib=106
    read and checked all 1 frames: SUCCESS     [duration: 179498 us  =  179.497600ms ]
  => SUCCESS
```

So for me everything is fine!

The code used to read is:
```
template<class TIMAGESAMPLETYPE>
void TEST_AGAINST_LIBTIFF(const char* filename, std::vector<TestResult>& test_results) {
#ifdef TINYTIFF_TEST_LIBTIFF
    HighResTimer timer, timer1;
    bool ok=false;
    std::cout<<"\n\nreading '"<<std::string(filename)<<"' with tinytiff and libtiff and checking read contents ... filesize = "<<bytestostr(get_filesize(filename))<<"\n";
    test_results.emplace_back();
    test_results.back().name=std::string("TEST_AGAINST_LIBTIFF(")+std::string(filename)+std::string(")");
    test_results.back().success=ok=false;
    try {
        timer.start();
        std::cout<<"    libTIFF: opening file with     [duration: "<<floattounitstr(double(timer.get_time())/1.0e6, "s")<<" ]\n";
        TIFF* ltiff=TIFFOpen(filename, "r");
        if (!ltiff) {
            std::cout<<"    libTIFF: ERROR reading (not existent, not accessible or no TIFF file)\n";
        } else {
            timer.start();
            uint32_t libTIFF_frames=TIFFCountDirectories(ltiff);
            double duration=timer.get_time();
            std::cout<<"    libTIFF: frames: "<<libTIFF_frames<<"     [duration: "<<duration<<" us  =  "<<floattounitstr(duration/1.0e6, "s")<<" ]\n";
            std::cout<<"    TinyTIFF: opening file with     [duration: "<<floattounitstr(double(timer.get_time())/1.0e6, "s")<<" ]\n";
            TinyTIFFReaderFile* tiffr=TinyTIFFReader_open(filename);
            if (!tiffr) {
                std::cout<<"    TinyTIFF: ERROR reading (not existent, not accessible or no TIFF file)\n";
                ok=false;
            } else if (TinyTIFFReader_wasError(tiffr)) {
                std::cout<<"   TinyTIFF: ERROR:"<<TinyTIFFReader_getLastError(tiffr)<<"\n";
                ok=false;
            } else {
                timer.start();
                uint32_t tinyTIFF_frames=TinyTIFFReader_countFrames(tiffr);
                duration=timer.get_time();
                std::cout<<"    TinyTIFF: frames: "<<tinyTIFF_frames<<"     [duration: "<<duration<<" us  =  "<<floattounitstr(duration/1.0e6, "s")<<" ]\n";
                if (TinyTIFFReader_wasError(tiffr)) {
                    std::cout<<"   TinyTIFF: ERROR:"<<TinyTIFFReader_getLastError(tiffr)<<"\n";
                    ok=false;
                } else {
                    if (libTIFF_frames!=tinyTIFF_frames) {
                        std::cout<<"    ERROR number of frames, read with TinyTIFF ("<<tinyTIFF_frames<<") and libTIFF ("<<libTIFF_frames<<") are not equal!\n";
                        ok=false;
                    } else {
                        timer.start();
                        size_t frame=0;
                        ok=true;
                        do {
                            std::cout<<"   frame: "<<frame<<std::endl;
                            uint32_t tinyTIFF_width=TinyTIFFReader_getWidth(tiffr);
                            uint32_t tinyTIFF_height=TinyTIFFReader_getHeight(tiffr);
                            uint16_t tinyTIFF_bitspersample=TinyTIFFReader_getBitsPerSample(tiffr, 0);
                            uint16_t tinyTIFF_samplesperpixel=TinyTIFFReader_getSamplesPerPixel(tiffr);
                            const char* tinyTIFF_imagedesc=TinyTIFFReader_getImageDescription(tiffr);
                            std::cout<<"     tinyTIFF: width="<<tinyTIFF_width<<", height="<<tinyTIFF_height<<", bitspersample="<<tinyTIFF_bitspersample<<", samplesperpixel="<<tinyTIFF_samplesperpixel<<"\n";
                            if (frame==0) {
                                const std::string desc=std::to_string(tinyTIFF_width)+"x"+std::to_string(tinyTIFF_height)+"pix/"+std::to_string(sizeof(TIMAGESAMPLETYPE)*8)+"bit/"+std::to_string(tinyTIFF_samplesperpixel)+"ch/"+std::to_string(tinyTIFF_frames)+"frames";
                                test_results.back().name=std::string("TEST_AGAINST_LIBTIFF(")+desc+", "+std::string(filename)+std::string(")");
                            }

                            uint32_t libTIFF_width=0;
                            uint32_t libTIFF_height=0;
                            uint32_t libTIFF_bitspersample=0;
                            uint32_t libTIFF_samplesperpixel=0;
                            char*libtiff_imagedesc;
                            TIFFGetField(ltiff,TIFFTAG_SAMPLESPERPIXEL,&libTIFF_samplesperpixel);
                            TIFFGetField(ltiff,TIFFTAG_BITSPERSAMPLE,&libTIFF_bitspersample);
                            TIFFGetField(ltiff,TIFFTAG_IMAGEWIDTH,&libTIFF_width);
                            TIFFGetField(ltiff,TIFFTAG_IMAGELENGTH,&libTIFF_height);
                            TIFFGetField(ltiff,TIFFTAG_IMAGEDESCRIPTION,&libtiff_imagedesc);
                            TIFFPrintDirectory(ltiff, stdout);
                            std::cout<<"     libTIFF:  width="<<libTIFF_width<<", height="<<libTIFF_height<<", bitspersample="<<libTIFF_bitspersample<<", samplesperpixel="<<libTIFF_samplesperpixel<<"\n";

                            if (tinyTIFF_width!=libTIFF_width) {
                                std::cout<<"       ERROR in frame "<<frame<<": TinyTIFF and libTIFF read different widths (TinyTIFF: "<<tinyTIFF_width<<" != libTIFF: "<<libTIFF_width<<")\n";
                                ok=false;
                                break;
                            }
                            if (tinyTIFF_height!=libTIFF_height) {
                                std::cout<<"       ERROR in frame "<<frame<<": TinyTIFF and libTIFF read different heights (TinyTIFF: "<<tinyTIFF_height<<" != libTIFF: "<<libTIFF_height<<")\n";
                                ok=false;
                                break;
                            }
                            if (tinyTIFF_bitspersample!=libTIFF_bitspersample) {
                                std::cout<<"       ERROR in frame "<<frame<<": TinyTIFF and libTIFF read different bitspersamples (TinyTIFF: "<<tinyTIFF_bitspersample<<" != libTIFF: "<<libTIFF_bitspersample<<")\n";
                                ok=false;
                                break;
                            }
                            if (tinyTIFF_samplesperpixel!=libTIFF_samplesperpixel) {
                                std::cout<<"       ERROR in frame "<<frame<<": TinyTIFF and libTIFF read different samplesperpixels (TinyTIFF: "<<tinyTIFF_samplesperpixel<<" != libTIFF: "<<libTIFF_samplesperpixel<<")\n";
                                ok=false;
                                break;
                            }
                            if (tinyTIFF_imagedesc==nullptr || libtiff_imagedesc==nullptr || strcmp(tinyTIFF_imagedesc, libtiff_imagedesc)!=0) {
                                std::cout<<"       WARNING in frame "<<frame<<": TinyTIFF and libTIFF read different descriptions (TinyTIFF: '"<<tinyTIFF_imagedesc<<"' != libTIFF: '"<<libtiff_imagedesc<<"')\n";
                                //ok=false;
                                //break;
                            }
                            if (ok) {
                                for (size_t sample=0; sample<libTIFF_samplesperpixel; sample++) {
                                    std::vector<TIMAGESAMPLETYPE> tinyTIFF_data(tinyTIFF_width*tinyTIFF_height*sizeof(TIMAGESAMPLETYPE)*2, 0);
                                    TinyTIFFReader_getSampleData(tiffr,tinyTIFF_data.data(), sample);
                                    if (TinyTIFFReader_wasError(tiffr)) {
                                        std::cout<<"       TinyTIFF: ERROR reading frame "<<frame<<", sample "<<sample<<":"<<TinyTIFFReader_getLastError(tiffr)<<"\n";
                                        ok=false;
                                    }
                                    if (ok) {
                                        std::vector<TIMAGESAMPLETYPE> libTIFF_data(libTIFF_width*libTIFF_height*sizeof(TIMAGESAMPLETYPE)*2, 0);
                                        if (!TIFFReadFrame(ltiff, libTIFF_data.data(), sample)) {
                                            std::cout<<"       libTIFF: ERROR reading frame "<<frame<<", sample "<<sample<<"\n";
                                            ok=false;
                                        }
                                        for (size_t i=0; i<libTIFF_data.size(); i++) {
                                            if (i<=8) std::cout<<"          f"<<frame<<"s"<<sample<<"i"<<i<<": tiny="<<std::dec<<static_cast<typename atleast_int<TIMAGESAMPLETYPE>::TPrint>(tinyTIFF_data[i])<<" lib="<<static_cast<typename atleast_int<TIMAGESAMPLETYPE>::TPrint>(libTIFF_data[i])<<"\n";
                                            if (libTIFF_data[i]!=tinyTIFF_data[i]) {
                                                std::cout<<"       ERROR in frame "<<frame<<", sample "<<sample<<": TinyTIFF and libTIFF read different sample values (I="<<i<<": TinyTIFF: "<<std::dec<<static_cast<typename atleast_int<TIMAGESAMPLETYPE>::TPrint>(tinyTIFF_data[i])<<" != libTIFF: "<<std::dec<<static_cast<typename atleast_int<TIMAGESAMPLETYPE>::TPrint>(libTIFF_data[i])<<")\n";
                                                ok=false;
                                                break;
                                            }
                                        }
                                    }
                                }
                            }


                            frame++;
                        } while (ok && TIFFReadDirectory(ltiff) && TinyTIFFReader_readNext(tiffr));

                        test_results.back().success=ok;
                        duration=timer.get_time();
                        test_results.back().duration_ms=duration/1.0e3;
                        std::cout<<"    read and checked all "<<frame<<" frames: "<<((ok)?std::string("SUCCESS"):std::string("ERROR"))<<"     [duration: "<<duration<<" us  =  "<<floattounitstr(duration/1.0e6, "s")<<" ]\n";
                    }
                }
            }
        }
    } catch(...) {
        ok=false;
        std::cout<<"       CRASH While reading file\n";
    }

    test_results.back().success=ok;
    if (ok) std::cout<<"  => SUCCESS\n";
    else std::cout<<"  => NOT CORRECTLY READ\n";
#endif
}
```

... Could you ensure that you're linking against the correct version of the lib? I just pushed a commit with new function TinyTIFFReader_getVersion() which outputs a version string including git-hash and compile-timestamp, e.g. "`3.0.0.0 (2020-10-09 14:58:09, Git: 5f87422)`"
Could you add a call+output to your code to ensure that you're linking against the correct lib?

Best,
JAN

**Comment by jkriege2** [comment]
Great!

**Comment by bala1144** [comment]
Hi,

I have talked with my supervisor, you can publish the images I provided as part of you test set.  Sorry for replying late. 

Thanks & Regards,
Bala
